package com.ce041;
// Generated 19 Apr, 2022 12:41:51 PM by Hibernate Tools 4.3.1



/**
 * Product generated by hbm2java
 */
public class Product  implements java.io.Serializable {


     private int pid;
     private String name;
     private int price;
     private int stock;
     private String image;

    public Product() {
    }

    public Product(int pid, String name, int price, int stock, String image) {
       this.pid = pid;
       this.name = name;
       this.price = price;
       this.stock = stock;
       this.image = image;
    }
   
    public int getpid() {
        return this.pid;
    }
    
    public void setPid(int pid) {
        this.pid = pid;
    }
    public String getPname() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public int getPrice() {
        return this.price;
    }
    
    public void setPrice(int price) {
        this.price = price;
    }
    public int getStock() {
        return this.stock;
    }
    
    public void setStock(int stock) {
        this.stock = stock;
    }
    public String getImage() {
        return this.image;
    }
    
    public void setImage(String image) {
        this.image = image;
    }




}


